### ISSUE TITLE
Specify minimum version of money gem

### ISSUE THREAD

**Issue by kriskhaira** [edlebert/money-oxr#1]
My project was on a very old version of money gem (6.5.0), and I got this error.

```
.../lib/active_support/dependencies.rb:274:in `require':
  cannot load such file -- money/rates_store/memory (LoadError)
```

Upgrading money to 6.10.1 fixed it for me, but it would be nice for other developers if a minimum version is specified so they get a warning upfront during `bundle install`.

Thank you.

**Comment by edlebert** [comment]
Thank you!  I will figure out a better minimum and update the gem.

**Comment by edlebert** [comment]
I added proper version (6.6) to gemspec in 0.3.0
