### ISSUE TITLE
URI.open deprecated method warning

### ISSUE THREAD

**Issue by johnboyes** [edlebert/money-oxr#13]
Hi, the following warning is emitted for [line 77 of `rates_store.rb`][1] when using the `money-oxr` gem (latest version 0.4.2):

```
rates_store.rb:77: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
```

[1]: https://github.com/edlebert/money-oxr/blob/132238701220649906d845bc171aabce43d270ff/lib/money_oxr/rates_store.rb#L77

**Comment by edlebert** [comment]
This was fixed in 0.4.3
